sudo: false
language: ruby
bundler_args: --deployment
cache: bundler
rvm:
  - 2.3.3
branches:
  only: master
services:
  - redis-server
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
